#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

source /usr/share/swap-file-creator/common

sanity_tests

if [ -f "$RUN_FOLDER/success" ]; then
   exit 0
else
   exit 1
fi
