#! /bin/bash
### BEGIN INIT INFO
# Provides:          swap-file-creator
# Required-Start:    $remote_fs $syslog mountkernfs
# Required-Stop:     $remote_fs $syslog
# Should-Start:      haveged
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Encrypted Swap File Creator
# Description:       Creates swap file encrypted with random password on boot
### END INIT INFO

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

source /usr/share/swap-file-creator/common

case "$1" in
   start)
      [ "$VERBOSE" != no ] && log_daemon_msg "$DESC" "$NAME"
      log_action_begin_msg "Starting $DESC"
      /usr/share/swap-file-creator/start
      log_end_msg 0
      ;;
   stop)
      log_action_begin_msg "Stopping $DESC"
      /usr/share/swap-file-creator/stop
      log_end_msg 0
      ;;
   restart|force-reload)
      log_action_begin_msg "Stopping $DESC"
      /usr/share/swap-file-creator/stop
      log_end_msg 0
      log_action_begin_msg "Starting $DESC"
      /usr/share/swap-file-creator/start
      log_end_msg 0
      ;;
   status)
      do_status_return_code="0"
      /usr/share/swap-file-creator/status || { do_status_return_code="$?" ; true; };
      if [ "$do_status_return_code" = "0" ]; then
         log_action_msg "$DESC ok"
      else
         log_action_msg "$DESC not active"
      fi
      exit "$do_status_return_code"
      ;;
   *)
      echo "Usage: $SCRIPTNAME (start|stop|restart|status)" >&2
      exit 3
      ;;
esac

true
