#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## bash fragment

## SWAP_FILE_SIZE_CUSTOM_MB
#SWAP_FILE_SIZE_CUSTOM_MB=2048

## verbose output
## defaults to:
## no
## possible values:
## yes
## no
#VERBOSE="no"

## Delete swapfile on shut down.
## defaults to:
## no
## possible values:
## yes
## no
#SHRED_ON_STOP="yes"

## shred options
#SHRED_OPTS="--verbose --iterations=3"

## shred extra options
#SHRED_EXTRA=""

## No change required unless you know what you are doing.
#UUID="0615ba72-85b0-4183-8d54-300bb0d2e491"

## No change required unless you know what you are doing.
#SWAPFILE="/var/swapfile"

## No change required unless you know what you are doing.
#MKSWAP_EXTRA=""

## No change required unless you know what you are doing.
#SWAPON_EXTRA=""

## No change required unless you know what you are doing.
#SWAPOFF_EXTRA=""

## No change required unless you know what you are doing.
#SWAPON_EXTRA="--verbose"

## No change required unless you know what you are doing.
#MAPPER="swapfile"

## No change required unless you know what you are doing.
#MAPPER_FULL="/dev/mapper/$MAPPER"

## Pass 'yes' or 'no' to calculate-swap-size.
## Otherwise auto detected. 'no' in VMs. 'yes' otherwise.
#HIBERNATION="no"
